- name: CI-Job
  hosts: local
  gather_facts: false

  tasks:
  
  - name: lint application
    shell: 
      cmd: tidy -q -e index.html
      #chdir: ~/environment/udacity-capstone-project/
      
  #- name: authenticate to ECR -> not necessary because amazon-ecr-credential-helper is used (https://github.com/awslabs/amazon-ecr-credential-helper)
    #command: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 731758322990.dkr.ecr.eu-central-1.amazonaws.com
    
  - name: create docker image
    command: docker build -t udacity-capstone-project:latest .
    
  - name: tag docker image
    command: docker tag udacity-capstone-project:latest 731758322990.dkr.ecr.eu-central-1.amazonaws.com/udacity-capstone-project:latest
    
  - name: remove old image from Amazon ECR
    command: aws ecr batch-delete-image --region eu-central-1 --repository-name udacity-capstone-project --image-ids imageTag=latest
    ignore_errors: yes
    
  - name: push new image to Amazon ECR
    command: docker push 731758322990.dkr.ecr.eu-central-1.amazonaws.com/udacity-capstone-project:latest
    
  - name: remove docker image
    command: docker rmi udacity-capstone-project:latest 731758322990.dkr.ecr.eu-central-1.amazonaws.com/udacity-capstone-project:latest
    ignore_errors: yes