- name: K8s-Job
  hosts: local
  gather_facts: false

  environment:
    KOPS_STATE_STORE: s3://k8sconfig.udacity.net

  tasks:
  
  - name: list s3 buckets
    command: aws s3 ls
    register: buckets
    
  - name: create S3 bucket (if not exists)
    command: aws s3 mb s3://k8sconfig.udacity.net
    when: buckets.stdout.find('test.udacity.net') == -1

  - name: create cluster configuration
    command: kops create cluster \
      --name k8s.udacity.net \
      --state ${KOPS_STATE_STORE} \
      --cloud aws \
      --master-size t2.micro \
      --master-count 1 \
      --master-zones eu-central-1a \
      --node-size t2.micro \
      --node-count 2 \
      --zones eu-central-1a,eu-central-1b \
      --dns-zone udacity.net \
      --dns private  \
      --ssh-public-key ~/.ssh/id_rsa.pub
      
  - name: spin up cluster with config
    command: kops update cluster --name k8s.udacity.net --yes
    
  #- name: validate cluster
  #  command: kops validate cluster --name k8s.udacity.net
  
  #- name: delete cluster
  #  command: kops delete cluster --name k8s.udacity.net --yes