- name: test play
  hosts: local
  gather_facts: false

  environment:
    KOPS_STATE_STORE: s3://k8sconfig.udacity.net

  tasks:

      - command: aws s3 ls
        #shell: cat test.yaml
        register: result

      - command: aws s3 mb s3://test.udacity.net
        when: result.stdout.find('test.udacity.net') == -1
        
     #- debug:
     #     var: shell_result.stdout_lines
        #when: shell_result.stdout.find('kjsdfjlsjfjdsf') != -1
      

  #  register: shell_result
  #- debug:
  #    var: shell_result.stdout_lines
  
  
#- name: test
  #  shell: |
  #    cd ~
  #    whoami
  #    aws configure list
  #    pwd
  #    ls workspace/UdacityCapstoneProject-CI-Job/*.html
  #  register: shell_result
  #- debug:
  #    var: shell_result.stdout_lines


#- name: Wait for servers to come online
#  wait_for:
#    host: "{{ item.public_ip }}"
#    port: 80
#    timeout: 180
#  with_items: "{{ ec2_instances.tagged_instances }}"
#  ignore_errors: True